### ISSUE TITLE
How to merge two xts, replacing NA's

### ISSUE THREAD

**Issue by stellathecat** [stellathecat/github#1]
Suppose I have a xts (data downloaded from IB) called fritz.

fritz[is.na(rowSums(fritz))]
unique(format(index(fritz[is.na(rowSums(fritz))]), '%Y-%m-%d'))

Now I check whether I have NA's, and download new data for these dates. However, I could happen that the new data also has NA's.

Is there a way to merge two xts, always taking the non-NA value?

**Comment by kurnosovv** [comment]
Merging for times series means binding columns together, the resulting xts will have all the columns from both xts. This is not what you need.
In your case, the most simple way will be to do it in data.frame style. I suppose that you downloaded new xts new_fritz which has the same dimension as fritz[is.na(rowSums(fritz))]. Then you just do replacing of data:

fritz[is.na(rowSums(fritz))] = new_fritz

and may again check NA's:

fritz[is.na(rowSums(fritz))]
unique(format(index(fritz[is.na(rowSums(fritz))]), '%Y-%m-%d'))

If new_fritz had NA's, then you should see them again, and then maybe repeat the operation. In such way you will keep fritz having the same size as initial xts, no dates will be removed. But if you wish to remove rows with NA's, then you may do it, remove data for some dates (in the end).
 
fritz = fritz[!is.na(rowSums(fritz))]

**Comment by kurnosovv** [comment]
Also you may use rbind to bind two xts objects together. In your case, you may use

fritz = rbind(fritz[!is.na(rowSums(fritz))], new_fritz)

if you want to keep the all the dates (so maybe there will be NA's from new_fritz), or

fritz = rbind(fritz[!is.na(rowSums(fritz))], new_fritz[!is.na(rowSums(new_fritz))])

if you want to remove all rows with NAs.
This is for your case when fritz[!is.na(rowSums(fritz))] and new_fritz do not have common indices (dates). Otherwise, in more general case, you will get xts object with duplicated index (it is allowed for xts). For omitting such situations, you will need to choose only those dates in the second xts, which are not present in the first xts.

**Comment by stellathecat** [comment]
Hi Vladi! You are right. The indices might not match. 

I tried the rbind solution before, and after that I did:
xx <- xx[ ! duplicated( index(xx) ),  ]

However, the problem was: This does not necessarily delete the non-NA duplicate. 
But your "rbind-solution" makes sure that there is no NA-value. So I can safely delete duplicates after this 👍 Thank you!
